import { Injectable } from '@angular/core';



/// SEPARATION APPLICATION USES THE SERVICE GENERATED BY JHIPSTER FOR NOW, LET'S FACTOR THAT OUT LATER

@Injectable({
  providedIn: 'root'
})
export class SeparationApplicationService {

  constructor() { }
}
